export const products = [
  { name: "Mydło", type: "Kosmetyki", quantity: 15 },
  { name: "Szampon", type: "Kosmetyki", quantity: 10 },
  { name: "Papier toaletowy", type: "Higiena", quantity: 30 },
  { name: "Pasta do zębów", type: "Higiena", quantity: 12 },
  { name: "Żel pod prysznic", type: "Kosmetyki", quantity: 8 },
  { name: "Gąbka kąpielowa", type: "Akcesoria łazienkowe", quantity: 5 },
  { name: "Środek do mycia szyb", type: "Chemia gospodarcza", quantity: 6 },
  { name: "Proszek do prania", type: "Chemia gospodarcza", quantity: 7 },
  { name: "Płyn do naczyń", type: "Chemia gospodarcza", quantity: 9 },
  { name: "Zeszyt", type: "Artykuły biurowe", quantity: 20 },
  { name: "Długopis", type: "Artykuły biurowe", quantity: 25 },
  { name: "Ołówek", type: "Artykuły biurowe", quantity: 18 },
  { name: "Klej", type: "Artykuły biurowe", quantity: 10 },
  { name: "Taśma klejąca", type: "Artykuły biurowe", quantity: 12 },
  { name: "Bateria AA", type: "Elektronika", quantity: 15 },
  { name: "Bateria AAA", type: "Elektronika", quantity: 10 },
  { name: "Latarka", type: "Elektronika", quantity: 5 },
  { name: "Ładowarka USB", type: "Elektronika", quantity: 7 },
  { name: "Przedłużacz", type: "Elektronika", quantity: 4 },
];
